# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='lent',
        ),
        migrations.AddField(
            model_name='instrument',
            name='available',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='addedAt',
            field=models.DateField(),
        ),
    ]
